version: '3.8'

services:
  # --- BACKEND ---
  backend:
    build: ./server
    container_name: fiszki-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=file:./database.sqlite
      - PORT=8080
      - CLIENT_URL=http://localhost:5173
    volumes:
      - ./server/prisma:/app/prisma
      - ./server:/app
      - /app/node_modules

  # --- FRONTEND ---
  frontend:
    build: ./client
    container_name: fiszki-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend